apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"port":30690,"protocol":"TCP","serviceName":"telem:nodered-nodeport","allNodes":true}]
    field.cattle.io/targetWorkloadIds: '["telem/nodered"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2024-03-07T13:43:01Z'
  name: nodered-nodeport
  namespace: telem
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: nodered
      uid: c80a4910-9f9e-4cfc-afaa-b26dd4619847
spec:
  clusterIP: 10.43.131.31
  clusterIPs:
    - 10.43.131.31
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 1880tcp
      nodePort: 30690
      port: 1880
      protocol: TCP
      targetPort: 1880
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-telem-nodered
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
