apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: telem
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: nodered
      uid: c80a4910-9f9e-4cfc-afaa-b26dd4619847
spec:
  clusterIP: 10.43.195.27
  clusterIPs:
    - 10.43.195.27
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 1880tcp
      port: 1880
      protocol: TCP
      targetPort: 1880
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-telem-nodered
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
